---
- hosts: localhost
  vars:
    ec2_enabled: yes
  roles:
    - ec2

- hosts: mcore
  roles:
    - firewalld
    - ansible
    - nodejs
    - docker
    - oc

#1
## Add Docker env vars
#  export DOCKERHUB_USERNAME=<my_dockerhub_username>
#  export DOCKERHUB_PASSWORD=<my_dockerhub_password>

#2 Fix mobile-core ansible scripts
## roles/oc-cluster-up
#  - remove lo:0 aliase
#  - change oc_version
#  - change public_hostname_ip
##  ui
#  - install bzip2 yum package

#3 ansible@2.4.2.0;docker@18.01.0-ce;pip@9.0.1;oc@3.7.1
# Setup cluster up with AWS EC2 instance
#$ metadata_endpoint="http://169.254.169.254/latest/meta-data"
#$ public_hostname="$( curl "${metadata_endpoint}/public-hostname" )"
#$ public_ip="$( curl "${metadata_endpoint}/public-ipv4" )"
#$ oc cluster up --public-hostname="${public_hostname}" --routing-suffix="${public_ip}.nip.io"