---
- hosts: centos
  roles:
    - minishift

########################################################################################################################
########################################################### VirtualBox
########################################################################################################################
#  - name: System | Get the current users name
#    shell: id -u -n
#    changed_when: false
#    ignore_errors: '{{ ansible_ignore_errors }}'
#    register: user_name
#    tags: [virtualbox, user]
#
#  - name: VirtualBox | Add repository
#    yum_repository:
#      name: VirtualBox
#      description: VirtualBox YUM repo
#      baseurl: http://download.virtualbox.org/virtualbox/rpm/el/$releasever/$basearch/
#      gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
#      gpgcheck: yes
#      enabled: yes
#    become: yes
#    tags: [virtualbox, packages]
#
#  - name: VirtualBox | Install required packages
#    yum:
#      name: '{{ item }}'
#      state: latest
#    with_items:
#      - binutils
#      - gcc
#      - make
#      - patch
#      - libgomp
#      - glibc-headers
#      - glibc-devel
#      - kernel-headers
#      - kernel-devel
#      - dkms
#    become: yes
#    tags: [virtualbox, dependencies]
#
#  - name: VirtualBox | Install VirtualBox@5.2
#    yum:
#      name: '{{ item }}'
#      state: latest
#    with_items:
#      - VirtualBox-5.2
#    become: yes
#    tags: [virtualbox, install]
#
#  - name: VirtualBox | Rebuild kernel modules
#    shell: /usr/lib/virtualbox/vboxdrv.sh setup
#    ignore_errors: no
#    register: virtualbox_kernel_modules_rebuilded
#    failed_when: virtualbox_kernel_modules_rebuilded.rc > 0
#    become: yes
#    tags: [virtualbox, install]
#
#  - name: VirtualBox | Add {{ user_name.stdout }} to vboxusers group
#    user:
#      name: '{{ user_name.stdout }}'
#      group: vboxusers
#      append: yes
#    become: yes
#    tags: [VirtualBox, install]




