---
########################################################################################################################
- hosts: localhost
  vars:
    ec2_enabled: no
  roles:
    - ec2

- hosts: centos
  roles:
    - mcore

#  - name: Ansible playbook run
#    command: >
#      ansible-playbook installer/playbook.yml
#      -e "dockerhub_username=$DOCKERHUB_USERNAME"
#      -e "dockerhub_password=$DOCKERHUB_PASSWORD"
#    args:
#      chdir: "~/mobile-core"
#    environment:
#      PATH: "{{ ansible_env.PATH}}:/home/{{ ansible_user }}/.local/bin"
#    changed_when: false
#    ignore_errors: no

# TODO check if we need setup cluster up with AWS EC2 instance
#$ metadata_endpoint="http://169.254.169.254/latest/meta-data"
#$ public_hostname="$( curl "${metadata_endpoint}/public-hostname" )"
#$ public_ip="$( curl "${metadata_endpoint}/public-ipv4" )"
#$ oc cluster up --public-hostname="${public_hostname}" --routing-suffix="${public_ip}.nip.io"
