---
- when: ansible_os_family == "RedHat"
  block:
  - name: Upgrade all packages
    yum:
      name: '*'
      state: latest
    become: yes
    tags: [system, install]

  - name: Install required packages
    yum:
      name: '{{ item }}'
      state: latest
    become: yes
    with_items: '{{ system_required_packages }}'
    tags: [system, packages]

  - name: Ensure the NTP service active and enabled
    systemd:
      name: ntpd
      state: started
      enabled: yes
    become: yes
    tags: [system, service]

  - name: Configure resolv.conf
    template:
      src: resolv.conf.j2
      dest: /etc/resolv.conf
      mode: 0644
    become: yes
    tags: [system, nameserver]

#TODO setup system limits
# echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

#TODO add MOTD file
#Managed by ansinle
#Some RHMAP-CORE logo
