- name: Clone mobile-core repo in ~/mobile-core
  git:
    repo: https://github.com/aerogear/mobile-core
    dest: ~/mobile-core
    refspec: '+refs/pull/*:refs/heads/*'
  register: mobile_core_cloned
  tags: [mcore, clone]

- name: Ansible galaxy install
  command: ansible-galaxy install -r installer/requirements.yml
  args:
    chdir: ~/mobile-core
  changed_when: mobile_core_cloned.changed
  register: ansible_galaxy_requirements_installed
  failed_when: ansible_galaxy_requirements_installed.rc > 0
  tags: [mcore, install]